language: generic

sudo: required
services:
    - docker

before_install:
    - docker build -t kwekuom/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true kwekuom/react-test npm test

after_success:
    - docker build -t kwekuom/multi-client ./client
    - docker build -t kwekuom/multi-nginx ./nginx
    - docker build -t kwekuom/multi-server ./server
    - docker build -t kwekuom/multi-worker ./worker
    # Log in to ther docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push them to docker hub
    - docker push kwekuom/multi-client
    - docker push kwekuom/multi-nginx
    - docker push kwekuom/multi-server
    - docker push kwekuom/multi-worker

deploy:
    edge: true
    provider: elasticbeanstalk
    region: eu-west-2
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-eu-west-2-199722415292
    bucket_path: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: 
        secure: $AWS_SECRET_KEY
        